# Greek letters lookup table
ascii_to_greek_letters = {
    "Alp": "α",
    "Bet": "β",
    "Chi": "χ",
    "Del": "δ",
    "Eps": "ε",
    "Eta": "η",
    "Gam": "γ",
    "Iot": "ι",
    "Kap": "κ",
    "Lam": "λ",
    "Mu": "μ",
    "Nu": "ν",
    "Ome": "ω",
    "Omi": "ο",
    "Phi": "φ",
    "Pi": "π",
    "Psi": "ψ",
    "Rho": "ρ",
    "Sig": "σ",
    "Tau": "τ",
    "The": "θ",
    "Ups": "υ",
    "Xi": "ξ",
    "Zet": "ζ",
}
